name: Deploy Docs

on:
  push:
    branches:
      - master
    paths:
      - "docs/**"
      - ".github/workflows/ci-deploy-docs.yaml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.2.1

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: pnpm

      - name: Configure corepack
        # Forcibly upgrade our available version of corepack.
        # The bundled version in node 16 has known issues.
        # Prepends the npm bin dir so that it is always first.
        shell: bash
        run: |
          npm install --force --global corepack@latest
          npm config get prefix >> $GITHUB_PATH
          corepack enable
      - name: Enable corepack
        if: ${{ inputs.enable-corepack == 'true' }}
        shell: bash
        run: |
          corepack enable
      - name: pnpm install
        shell: bash
        run: pnpm install

      - name: Build
        run: pnpm docs:build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: docs/docs/.vitepress/dist
